apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-api-limits
  namespace: team-api
spec:
  hard:
    limits.cpu: "400m"
    limits.memory: "810Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: team-api-limit-range
  namespace: team-api
spec:
  limits:
  - max:
      cpu: 1
      memory: 100Mi
    type: Container
